/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tgnjkhqhjqyrjeuadlec"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnbmpraHFoanF5cmpldWFkbGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjU4NTksImV4cCI6MjA5MTM0MTg1OX0.KWic-crQwjqu22389-NuCzwAPUnwh8F37eMY8v_H0nc"